

import Head from "next/head";
import { useRef, useState, useEffect } from "react";
import { FaWhatsapp } from "react-icons/fa";
import VoteModal from "../components/VoteModal";

export default function Home() {
  const audioRefs = useRef({
    audio1: null,
    audio2: null,
    audio3: null,
    audio4: null,
  });

  // State for controlling button colors and modal visibility
  const [isRed, setIsRed] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isVoteModalOpen, setIsVoteModalOpen] = useState(false);
  const [voteCount, setVoteCount] = useState(0);
  const [isVoting, setIsVoting] = useState(false);

  const handleAudioPlay = (audioKey) => {
    if (audioRefs.current[audioKey]) {
      audioRefs.current[audioKey].play();
    }
  };

  const handleButtonClick = async () => {
    setIsRed(true); // Change circle color to red
    setIsVoting(true);
    handleAudioPlay("audio3"); // Play Button Beep sound
    handleAudioPlay("audio4");

    try {
      const response = await fetch('/api/votes', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        credentials: 'same-origin',
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to submit vote');
      }
      
      const data = await response.json();
      setVoteCount(data.count);
      setIsModalOpen(true); // Open modal to show confirmation
      
    } catch (error) {
      console.error('Error submitting vote:', error);
      alert(`Vote submission failed: ${error.message}`);
    } finally {
      setIsVoting(false);
    }
  };

  const handleButtonClick1 = () => handleAudioPlay("audio1");
  const handleButtonClick2 = () => handleAudioPlay("audio2");

  const fakeLinkRef = useRef(null);

  const handleButtonWhatsapp = () => {
    const currentUrl = window.location.href;
    const whatsappUrl =
      "https://api.whatsapp.com/send?text=" +
      encodeURIComponent(currentUrl) +
      "%0D%0Aमी डेमो मतदान केले, तुम्ही केले का?";

    fakeLinkRef.current.setAttribute("href", whatsappUrl);
    fakeLinkRef.current.click();
  };

  useEffect(() => {
    let timer;
    if (isRed) {
      timer = setTimeout(() => setIsRed(false), 2000); // Reset after 2 seconds
    }
    return () => clearTimeout(timer); // Cleanup on unmount or state change
  }, [isRed]);

  const handleCloseModal = () => setIsModalOpen(false); // Close modal

  return (
    <>
      <Head>
        <title>सौ. ॲड प्रणोती सागर निंबोरेकर (भोंडेकर)</title>
        <meta name="description" content="Generated by Eesweb.in" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4 bg-white max-w-xl mx-auto text-center">
        <h1 className="text-lg font-semibold text-blue-800">
        गडचिरोली नगरपरिषद निवडणूक – २०२५
        </h1>
        <h2 className="text-2xl font-bold text-red-600 mt-2">डमी मतदान यंत्र</h2>
        <button
          className="bg-indigo-800 text-white py-2 px-4 rounded-md text-lg mt-4 shadow-md"
          onClick={handleButtonClick2}
        >
          डेमो मतदानासाठी कमळ निशाणी समोरील निळे बटन दाबावे
        </button>
        <p className="text-md font-medium mt-6">
          मतदानाच्या दिवशी सुद्धा <span className="font-bold">कमळ</span> या
          चिन्हासमोरील बटन दाबून{" "}
          <span className="font-bold">सौ. ॲड प्रणोती सागर निंबोरेकर (भोंडेकर)</span> यांना प्रचंड मतांनी
          विजयी करा !
        </p>
        <div className="flex justify-center mt-6 gap-2 flex-wrap">
          <button
            className="bg-green-500 text-white font-bold py-2 px-4 rounded-full flex items-center space-x-2"
            onClick={handleButtonWhatsapp}
          >
            <FaWhatsapp />
            <span>SHARE</span>
          </button>
          {/* <a href="https://wa.link/92x71l">
            <button className="bg-green-500 text-white font-bold py-2 px-4 rounded-full flex items-center space-x-2">
              <span>MESSAGE</span>
            </button>
          </a> */}
        </div>
      </div>

      <div className="bg-yellow-400 text-center py-4 px-6">
        <p className="text-black font-bold text-3xl">
          “कमळ” या चिन्हासमोरील बटन दाबून प्रचंड मतांनी विजयी करा.
        </p>
        <p className="text-black text-xl mt-2">
          मतदान दिनांक ०२ डिसेंबर २०२५ स. ०७:०० ते सायं. ०६:००
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="table-auto w-full border-2 border-solid  border-black">
          <thead>
            <tr>
              <th className="border-2  border-black p-2 font-semibold">अ.क्र</th>
              <th className="border-2 border-r-0  border-black p-2  font-semibold">उमेदवाराचे नाव</th>
              <th className=""></th>
              <th className="border-2 border-black p-2 font-semibold">चिन्ह</th>
              <th className="border-2 border-black font-semibold bg-orange-100">बटन</th>
            </tr>
          </thead>
          <tbody>
           

            <tr>
              <td className="border-2 border-black p-2 text-center text-xl font-bold">१.</td>
              <td className="border-2 border-black text-center text-sm font-bold w-65">
              सौ. ॲड प्रणोती सागर निंबोरेकर (भोंडेकर)
              </td>
              <td className="border-2 border-black text-center w-16">
                <img src="/tai.png" className="m-auto" />
              </td>
              <td className="border-2 border-black text-center w-16">
                <img src="/kamal.png" className=" " />
              </td>
              <td className="border-2 border-black p-4 bg-orange-100 text-center flex flex-row justify-center">
                <div
                  className={`w-8 h-6 rounded-full border-2 border-black inline-block mr-2 ${
                    isRed ? "bg-red-500" : ""
                  }`}
                ></div>
                <button
                  onClick={handleButtonClick}
                  className="bg-blue-900 text-white rounded-full px-4 shadow-lg"
                >
                  बटण दाबा
                </button>
              </td>
            </tr>
            <tr>
              <td className="border-2 border-black text-center">२.</td>
              <td className="border-2 border-black "></td>
              <td className="border-2 border-black "></td>
              <td className="border-2 border-black text-center"></td>
              <td className="border-2 border-black bg-orange-100 text-center">
                <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
                <button
                  className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"
                  onClick={handleButtonClick1}
                ></button>
              </td>
            </tr>
            
            <tr>
         <td className="border-2 border-black  text-center">३.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">४.</td>
         <td className="border-2 border-black  text-center"></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">५.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">६.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">७.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">८.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black text-center">९.</td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१०.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">११.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१२.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१३.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१४.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block  mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१५.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black text-center">१६.</td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black text-center">१७.</td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१८.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black  text-center">१९.</td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black "></td>
         <td className="border-2 border-black  text-center">
         </td>
         <td className="border-2 border-black  bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>
       <tr>
         <td className="border-2 border-black text-center">२०.</td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black"></td>
         <td className="border-2 border-black text-center">
         </td>
         <td className="border-2 border-black bg-orange-100 text-center  ">
         <div className="w-6 h-6 rounded-full border-2 border-black inline-block mr-2"></div>
           <button className="bg-blue-900 text-white rounded-full px-8 py-4 shadow-lg"onClick={handleButtonClick1}></button>
         </td>
      </tr>


          </tbody>
        </table>
      </div>
      <div className="flex justify-between items-center p-4 text-gray-600 text-sm">
    <span>2024 © <a href="https://shakktii.in" className="text-blue-500 hover:underline">SHAKKTII.IN</a></span>
    <span className="flex items-center">
        Crafted with <span className="text-red-500 px-1">❤️</span> by 
        <a href="tel:+919551339292" className="text-blue-500 hover:underline ml-1">+91 8956668867</a>
    </span>
</div>

      <audio ref={(el) => (audioRefs.current.audio1 = el)} src="/x.mp4" preload="auto"></audio>
      <audio ref={(el) => (audioRefs.current.audio2 = el)} src="/B1.wav" preload="auto"></audio>
      <audio ref={(el) => (audioRefs.current.audio3 = el)} src="/ButtonBeep.WAV" preload="auto"></audio>
      <audio ref={(el) => (audioRefs.current.audio4 = el)} src="/B3.wav" preload="auto"></audio>

      {isModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-70 flex flex-col justify-center items-center z-50">
                  <div className="relative bg-white rounded-lg p-8 text-center">
                    <button
                      onClick={handleCloseModal}
                      className="absolute top-4 right-4 text-gray-600 text-2xl font-bold"
                    >
                      ✕
                    </button>
                    <img 
  src="/Amit.gif" 
  alt="Full-screen" 
  className="w-44 h-auto mb-4"
/>
                    {/* <div className="mt-4">
                      <p className="text-2xl font-bold text-blue-800 mb-2">Vote Counted!</p>
                      <p className="text-5xl font-bold text-green-600 mb-4">{voteCount}</p>
                      <p className="text-gray-600 text-lg">Total Votes</p>
                    </div> */}
                  </div>
                  <div className="mt-4">
                  {/* <a href="https://wa.link/92x71l">
                <button className="bg-green-500 text-white font-bold py-2 px-4 rounded-full flex items-center space-x-2">
                    <span>MESSAGE</span>
                </button>
            </a> */}
                  <button className="bg-green-500 mr-2 text-white font-bold py-2 px-4 rounded-full flex items-center space-x-2" onClick={handleButtonWhatsapp}>
                <FaWhatsapp />
                    <span>SHARE</span>
                </button>
                </div>
                </div>
      )}

      <VoteModal 
        isOpen={isVoteModalOpen} 
        onClose={() => setIsVoteModalOpen(false)} 
      />

      <a ref={fakeLinkRef} href="#" style={{ display: "none" }} />
    </>
  );
}
